# try-catch

## 오류란?

컴파일 시 문법적인 오류와 런타임 시 널포인트 참조와 같은 오류로 프로세스에 심각한 문제를 야기시켜 프로세스를 종료 시킬 수 있다.

프로그램 코드로 처리 할 수 없다

## 예외란?

프로그램을 만든 프로그래머가 상정한 정상적인 처리를 벗어난 경우

컴퓨터 시스템의 동작 도중 예기치 않았던 이상 상태가 발생하여 수행 중인 프로그램이 영향을 받는 것

프로그램 코드로 비정상적인 종료를 막을 수 있다.

## 예외 처리란?

예외를 처리하기 위한 방법

## JS의 예외 처리

### try...catch

```jsx
try{
  // 코드
} catch (e) {
  // 에러 핸들링
}
```

1. ```try{...}``` 안의 코드가 실행된다
2. 에러가 없다면, ```try```안의 코드가 끝까지 실행되고, catch 블록은 건너 뛴다
3. 에러가 있다면, ```try```안의 코드의 싫앵이 중단되고, catch(err) 블록으로 제어 흐름이 넘어간다.

try 블록 안에서 에러가 발생해도 catch 에서 에러를 처리하기 때문에 스크립트가 죽지 않는다.

### finally

```jsx
try {
  // 코드
} catch (e) {
  // 에러 핸들링
} finally{
  // 코드
}
```

없어도 되는 문장이지만, 마지막에 실행이 꼭 필요한 문장이 있을 때 사용한다

try문 뒤에는 catch 또는 finally 둘중 하나는 있어야 한다

### throw

인위적으로 에러를 발생시키는 문법

```jsx
try {
  throw("new message");
}catch(e){
  // 에러 핸들링
}
```

### new Error

throw로 넘기지만 Error 객체를 생성한다

에러 핸들링을 할 때, e.message의 형태로 받아줘야한다

```jsx
try{
  throw new Error("new message");
}catch(e){
  console.log(e.message);
}
```

## 에러 객체

에러가 발생하면 JS는 에러 상세내용이 담긴 객체를 생성한다

```catch``` 블록에 이 객체를 인수로 전달한다.

### 주요 프로퍼티

- name : 에러 이름, 정의되지 않은 변수 때문에 발생한 에러라면 "ReferanceError"가 이름이 된다
- message : 에러 상세 내용을 담고 있는 문자 메시지

### 비표준 프로퍼티

- stack : 현재 호출 스택, 에러를 유발한 중첩 호출들의 순서 정보를 가진 문자열로 디버깅 목적으로 사용된다

## 주의 사항

### 런타임 에러에만 동작한다

```try..catch```는 실행 가능한 코드에만 동작한다 (유효한 자바스크립트 코드를 의미한다)

코드가 문법적으로 잘못된 경우엔 ```try..catch``가 동작하지 않는다

### try..catch는 동기적으로 동작한다

setTimeout처럼 스케줄 된 코드에서 발생한 예외는 ```try..catch```에서 잡아낼 수 없다